package me.n1ar4.jar.analyzer.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import me.n1ar4.jar.analyzer.gui.util.SyntaxAreaHelper;
import me.n1ar4.jar.analyzer.utils.StringUtil;

import javax.swing.*;
import java.awt.*;

public class SearchForm {
    private JPanel rootPanel;
    private JTextField searchText;
    private JButton searchBtn;
    private JLabel searchLabel;
    private JButton prevButton;
    private JButton nextButton;
    private JLabel resultLabel;
    private static SearchForm instance;
    private static String searchTextGlobal = null;
    private static int total = 0;

    public static void start() {
        JFrame frame = new JFrame();
        instance = new SearchForm();
        instance.init();
        frame.setContentPane(instance.rootPanel);
        frame.pack();
        frame.setAlwaysOnTop(true);
        frame.setLocationRelativeTo(MainForm.getInstance().getMasterPanel());
        frame.setVisible(true);
        frame.setResizable(false);
    }

    private void init() {
        resultLabel.setText("0/0");
        instance.searchBtn.addActionListener(e -> {
            String text = searchText.getText();
            // 修复卡死的 BUG
            if (StringUtil.isNull(text)) {
                JOptionPane.showMessageDialog(rootPanel, "search text is empty");
                return;
            }
            searchTextGlobal = text;
            total = SyntaxAreaHelper.addSearchAction(text);
            if (total == 0) {
                resultLabel.setText("0/0");
                return;
            }
            int cur = SyntaxAreaHelper.getCurrentIndex();
            resultLabel.setText(String.format("%d/%d", cur + 1, total));
        });
        instance.prevButton.addActionListener(e -> {
            if (searchTextGlobal == null || searchTextGlobal.isEmpty()) {
                return;
            }
            if (total == 0) {
                return;
            }
            SyntaxAreaHelper.navigate(searchTextGlobal, false);
            int cur = SyntaxAreaHelper.getCurrentIndex();
            resultLabel.setText(String.format("%d/%d", cur + 1, total));
        });
        instance.nextButton.addActionListener(e -> {
            if (searchTextGlobal == null || searchTextGlobal.isEmpty()) {
                return;
            }
            if (total == 0) {
                return;
            }
            SyntaxAreaHelper.navigate(searchTextGlobal, true);
            int cur = SyntaxAreaHelper.getCurrentIndex();
            resultLabel.setText(String.format("%d/%d", cur + 1, total));
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 2, new Insets(5, 5, 5, 5), -1, -1));
        searchLabel = new JLabel();
        searchLabel.setText("Search Text");
        rootPanel.add(searchLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        searchText = new JTextField();
        rootPanel.add(searchText, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(150, -1), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panel1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        searchBtn = new JButton();
        searchBtn.setText("Search");
        panel1.add(searchBtn, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        prevButton = new JButton();
        prevButton.setText("Prev");
        panel1.add(prevButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nextButton = new JButton();
        nextButton.setText("Next");
        panel1.add(nextButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resultLabel = new JLabel();
        resultLabel.setText("0");
        panel1.add(resultLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
