/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_n1ar4_jar_analyzer_utils_ConsoleUtils */

#ifndef _Included_me_n1ar4_jar_analyzer_utils_ConsoleUtils
#define _Included_me_n1ar4_jar_analyzer_utils_ConsoleUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_n1ar4_jar_analyzer_utils_ConsoleUtils
 * Method:    setWindowsColorSupport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_n1ar4_jar_analyzer_utils_ConsoleUtils_setWindowsColorSupport
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
