name: maven check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  check:
    name: maven check (jdk ${{ matrix.java-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ '8', '17', '25' ]
    steps:
    - uses: actions/checkout@v6
    - name: set up java ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    - name: check core maven
      run: mvn -B clean package -DskipTests --file pom.xml
    - name: check agent maven
      run: cd agent && mvn -B clean package -DskipTests --file pom.xml
